-- MySQL Script generated by MySQL Workbench
-- Di 24 Mai 2016 15:54:13 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CatTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CatTable` (
  `IDcat` INT NOT NULL COMMENT '',
  `name` MEDIUMTEXT NOT NULL COMMENT '',
  PRIMARY KEY (`IDcat`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RefTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RefTable` (
  `IDref` INT NOT NULL COMMENT '',
  `IDcat` INT NOT NULL COMMENT '',
  `path` MEDIUMTEXT NOT NULL COMMENT '',
  PRIMARY KEY (`IDref`)  COMMENT '',
  INDEX `IDcat_idx` (`IDcat` ASC)  COMMENT '',
  CONSTRAINT `IDcat`
    FOREIGN KEY (`IDcat`)
    REFERENCES `mydb`.`CatTable` (`IDcat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserTable` (
  `IDuser` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`IDuser`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TagTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TagTable` (
  `IDtag` INT NOT NULL COMMENT '',
  `name` MEDIUMTEXT NULL COMMENT '',
  PRIMARY KEY (`IDtag`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LogTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LogTable` (
  `IDlog` INT NOT NULL COMMENT '',
  `rate` VARCHAR(45) NULL COMMENT '',
  `note` LONGTEXT NULL COMMENT '',
  `date` VARCHAR(45) NOT NULL COMMENT '',
  `IDuser` INT NOT NULL COMMENT '',
  PRIMARY KEY (`IDlog`)  COMMENT '',
  INDEX `IDuser_idx` (`IDuser` ASC)  COMMENT '',
  CONSTRAINT `IDuser`
    FOREIGN KEY (`IDuser`)
    REFERENCES `mydb`.`UserTable` (`IDuser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TagRefTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TagRefTable` (
  `IDref` INT NOT NULL COMMENT '',
  `IDtag` INT NOT NULL COMMENT '',
  PRIMARY KEY (`IDref`, `IDtag`)  COMMENT '',
  INDEX `IDtag_idx` (`IDtag` ASC)  COMMENT '',
  CONSTRAINT `IDref`
    FOREIGN KEY (`IDref`)
    REFERENCES `mydb`.`RefTable` (`IDref`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IDtag`
    FOREIGN KEY (`IDtag`)
    REFERENCES `mydb`.`TagTable` (`IDtag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TimelineRefTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TimelineRefTable` (
  `IDlog` INT NOT NULL COMMENT '',
  `IDref` INT NOT NULL COMMENT '',
  `duration` INT NOT NULL COMMENT '',
  PRIMARY KEY (`IDlog`, `IDref`)  COMMENT '',
  INDEX `IDref_idx` (`IDref` ASC)  COMMENT '',
  CONSTRAINT `IDref`
    FOREIGN KEY (`IDref`)
    REFERENCES `mydb`.`RefTable` (`IDref`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IDlog`
    FOREIGN KEY (`IDlog`)
    REFERENCES `mydb`.`LogTable` (`IDlog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
